spring.application.name=mvp_m6
app.app-name=E-TravelGo

spring.datasource.url =jdbc:mysql://localhost:3306/etravelgo
spring.datasource.username=root
spring.datasource.password=Root1234*
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false

spring.mvc.hiddenmethod.filter.enabled=true
